spring:
  #jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
      multipart:
       enabled: true
       max-file-size: 1024MB
       max-request-size: 1024MB
    # druid 配置：
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
          first:  #数据源1
              url: jdbc:mysql://www.xddal.com:3306/optimal?useUnicode=true&characterEncoding=utf8&useSSL=false
              username: root
              password: xd123456
          second:  #数据源2
              url: jdbc:mysql://www.xddal.com:3306/optimal?useUnicode=true&characterEncoding=utf8&useSSL=false
              username: root
              password: xd123456
          initial-size: 10
          max-active: 100
          min-idle: 10
          max-wait: 60000
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          stat-view-servlet:
              enabled: true
              url-pattern: /druid/*
              #login-username: admin
              #login-password: admin
          filter:
              stat:
                  log-slow-sql: true
                  slow-sql-millis: 1000
                  merge-sql: true
              wall:
                  config:
                      multi-statement-allow: true


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  #注意：一定要对应mapper映射xml文件的所在路径mapper/*.xml
  mapper-locations: classpath:*/*Mapper.xml
  # 注意：对应实体类的路径
  type-aliases-package: com.xddal.moon.auto.entity
  configuration:
    #开启MyBatis的二级缓存
    cache-enabled: false


#pagehelper分页插件
pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql

logging:
  level:
   root: INFO